Rails.application.routes.draw do
  get '/' => 'auditoriums#index'
  get '/auditoriums' => 'auditoriums#index'
  get '/auditoriums/new' => 'auditoriums#new'
  post '/auditoriums' => 'auditoriums#create'
  get '/auditoriums/:id' => 'auditoriums#show'
  get '/auditoriums/:id/edit' => 'auditoriums#edit'
  patch '/auditoriums/:id' => 'auditoriums#update'
  delete '/auditoriums/:id' => 'auditoriums#destroy'

  get '/' => 'customers#index'
  get '/customers' => 'customers#index'
  get '/customers/new' => 'customers#new'
  post '/customers' => 'customers#create'
  get '/customers/:id' => 'customers#show'
  get '/customers/:id/edit' => 'customers#edit'
  patch '/customers/:id' => 'customers#update'
  delete '/customers/:id' => 'customers#destroy'

  get '/' => 'movies#index'
  get '/movies' => 'movies#index'
  get '/movies/new' => 'movies#new'
  post '/movies' => 'movies#create'
  get '/movies/:id' => 'movies#show'
  get '/movies/:id/edit' => 'movies#edit'
  patch '/movies/:id' => 'movies#update'
  delete '/movies/:id' => 'movies#destroy'

  get '/' => 'movietheaters#index'
  get '/movietheaters' => 'movietheaters#index'
  get '/movietheaters/new' => 'movietheaters#new'
  post '/movietheaters' => 'movietheaters#create'
  get '/movietheaters/:id' => 'movietheaters#show'
  get '/movietheaters/:id/edit' => 'movietheaters#edit'
  patch '/movietheaters/:id' => 'movietheaters#update'
  delete '/movietheaters/:id' => 'movietheaters#destroy'

  get '/' => 'seats#index'
  get '/seats' => 'seats#index'
  get '/seats/new' => 'seats#new'
  post '/seats' => 'seats#create'
  get '/seats/:id' => 'seats#show'
  get '/seats/:id/edit' => 'seats#edit'
  patch '/seats/:id' => 'seats#update'
  delete '/seats/:id' => 'seats#destroy'

  get '/' => 'showtimes#index'
  get '/showtimes' => 'showtimes#index'
  get '/showtimes/new' => 'showtimes#new'
  post '/showtimes' => 'showtimes#create'
  get '/showtimes/:id' => 'showtimes#show'
  get '/showtimes/:id/edit' => 'showtimes#edit'
  patch '/showtimes/:id' => 'showtimes#update'
  delete '/showtimes/:id' => 'showtimes#destroy'

  get '/' => 'tickets#index'
  get '/tickets' => 'tickets#index'
  get '/tickets/new' => 'tickets#new'
  post '/tickets' => 'tickets#create'
  get '/tickets/:id' => 'tickets#show'
  get '/tickets/:id/edit' => 'tickets#edit'
  patch '/tickets/:id' => 'tickets#update'
  delete '/tickets/:id' => 'tickets#destroy'

  get '/' => 'users#index'
  get '/users' => 'users#index'
  get '/users/new' => 'users#new'
  post '/users' => 'users#create'
  get '/users/:id' => 'users#show'
  get '/users/:id/edit' => 'users#edit'
  patch '/users/:id' => 'users#update'
  delete '/users/:id' => 'users#destroy'

  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end